/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visualization;

import java.awt.Color;
import java.awt.Graphics;
import java.util.List;
import tareaasignacionmemoriaso.Bloque;
import tareaasignacionmemoriaso.Proceso;
/**
 *
 * @author Dell
 */
public class Visualization extends javax.swing.JFrame {

    static int memory = 1000;
    private List<Proceso> processes;
    public Visualization(List<Proceso> processes){
        this.processes = processes;
        setTitle("Tutorial");
        setSize(memory+20, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    public void updateWindow(List<Proceso> processes){
        setVisible(false);
        this.processes = processes;
        setVisible(true);
    }
    
    
    public void paint(Graphics g) {
        int y = 50;
        for(Proceso process: processes ){
            for(Bloque block: process.getAllocatedBlocksFirst() ){
                
                g.setColor(process.getColor());
                g.fillRect(block.getAddress(),y, block.getAddress()+block.getMemory(), 50);   
            } 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
